config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'languages#index'
  resources :users
  resources :languages
  resources :snippets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user, optional: true
  has_many   :snippets, dependent: :destroy
  
  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :language, optional: true
  
  validates :title, presence: true
  validates :code, presence: true
  validates :language_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :languages, dependent: :destroy
  has_many :snippets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_languages, only: [:index, :new, :create]
  def index
  end
  
  def show
  end
  
  def new
    @language = Language.new
  end
  
  def create
    @language = Language.new(language_params)
    @language.user_id = current_user.id
    if @language.save
      redirect_to root_path
      flash[:success] = "登録しました"
    else
      flash[:danger] = "エラー"
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @language = Language.find(params[:id])
    if @language.destroy
      flash[:success] = "カテゴリーを削除しました"
      redirect_to root_path
    else
      flash[:danger] = "エラー"
    end
  end
  
  private
    def language_params
      params.require(:language).permit(:name, user_id: params[:user_id])
    end
    
    def set_languages
      @languages = Language.all
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
  end
  
  def show
    @snippet = Snippet.find(params[:id])
    @language = Language.find(@snippet.language_id)
  end
  
  def new
    @snippet = Snippet.new
  end
  
  def create
    @snippet = Snippet.new(snippet_params)
    @snippet.language_id = params[:snippet][:language_id]
    if @snippet.save
      redirect_to @snippet
      flash[:success] = "登録しました"
    else
      flash[:danger] = "エラー"
      render :new
    end
  end
  
  def edit
    @snippet = Snippet.find(params[:id])
  end
  
  def update
    snippet = Snippet.find(params[:id])
    snippet.language_id = params[:snippet][:language_id]
    if snippet.update(snippet_params)
      redirect_to snippet_path
      flash[:success] = "更新しました"
    else
      flash[:danger] = "エラー"
      render :new
    end
  end
  
  def destroy
    @snippet = Snippet.find(params[:id])
    if @snippet.destroy
      redirect_to root_path
      flash[:success] = "スニペットを削除しました"
    else
      flash[:danger] = "エラー"
    end
    
  end
  
  private
  def snippet_params
    params.require(:snippet).permit(:title, :code, :comment, language_id: params[:language_id])
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/languages/index.html.erb
<div class="wrapper">
  <%= render partial: "shared/sidebar" %>
  <div class="main">
    <div id="howto">
      <div class="card">
        <h1 class="card-header">使い方</h1>
        <div class="card-body">
          <p>まずは<span class="card bg-dark">カテゴリー登録</span>からカテゴリーを登録します。</p>
          <P>次に<span class="card bg-dark">スニペット登録</span>でコードを登録します。</P>
          <p>サイドバーからスニペットの詳細が確認できます。</p>
          <P>詳細画面で編集・削除が可能です。</P>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/languages/new.html.erb
<div class="wrapper">
  <%= render partial: "shared/sidebar" %>
  <div class="main">
    <div class="container">
      <div class="language-form">
        <%= form_with(model: @language, local: true) do |form| %>
          <div class="form-group row">
            <div class="col-md-8">
              <p>カテゴリー</p>
              <%= form.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group col-md-4">
              <%= form.submit "登録", class: 'btn btn-dark position' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippet Reserve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=sons-of-obsidian'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render partial: "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand navbar-brand-center" href="/">Snippet Reserve</a>
  <div class="collapse navbar-collapse justify-content-end">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "ユーザー情報編集", edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="/users/sign_up">新規登録</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav> 

app/views/shared/_sidebar.html.erb
<div class="side_bar">
  <div class="operate">
    <div class="btn bg-dark">
      <%= link_to "カテゴリー登録", new_language_path(current_user) %>
    </div>
    <div class="btn bg-dark">
      <%= link_to "スニペット登録",  new_snippet_path %>
    </div>
  </div>
  <div class="languages">
    <ul class="accordion card">
      <% current_user.languages.sort_by(&:name).each do |language| %>
        <li>
          <div class="language card-header">
            <div class="language_name">
              <%= language.name %>
            </div>
            <div class="language_delete">
              <%= link_to "削除", language_path(language.id), method: 'DELETE', data: { confirm: '削除しますか？' } %>
            </div>
          </div>
          <ul>
            <% language.snippets.sort_by(&:title).each do |snippet| %>
              <li data-jstree='{ "icon" : "none" }'>
                <div class="snippet list-group-flush">
                  <div class="snippet_name">
                    <%= link_to snippet.title, snippet_path(snippet.id) %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<script>
$(function(){
    //.accordionの中のliの中のulの初期値を非表示に
  $('.accordion li ul').toggle();
    //.accordionの中の.language_name要素がクリックされたら
	$('.accordion .language_name').click(function(){
		//クリックされた.accordionの中の.language_mname要素の親要素に隣接するul要素が開いたり閉じたりする。
		$(this).parent().next('ul').slideToggle(150);
	});
});
</script>

app/views/snippets/_form.html.erb
<div class=container>
  <%= form_with(model: @snippet, local: true) do |form| %>
    <div class="form-group row">
      <div class="col-sm-4">
        <p>タイトル</p>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="col-sm-4">
        <p>カテゴリー</p>
        <%= form.collection_select :language_id, current_user.languages, :id, :name,
          {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= form.submit "登録", class: 'btn btn-dark position' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-8">
        <p>コード</p>
        <%= form.text_area :code, class: 'form-control', rows: "12", wrap: "off" %>
      </div>
      <div class="col-sm-4">
        <p>コメント</p>
        <%= form.text_area :comment, class: 'form-control', rows: "12", wrap: "off" %>
      </div>
    </div>

  <% end %>
  </div>

app/views/snippets/edit.html.erb
<div class="wrapper">
  <%= render partial: "shared/sidebar" %>
  <div class="main">
    <%= render partial: 'form', locals:{ snippet: @snippet } %>
  </div>
</div>

app/views/snippets/new.html.erb
<div class="wrapper">
  <%= render partial: "shared/sidebar" %>
  <div class="main">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/snippets/show.html.erb
<div class="wrapper">
  <%= render partial: "shared/sidebar" %>
  <div class="main">
    <div class=container>
      <div class="form-group row">
        <div class="col-md-4">
          <p>タイトル</p>
          <div class="form-control">
            <%= @snippet.title %>
          </div>
        </div>
        <div class="col-md-4">
          <p>カテゴリー</p>
          <div class="form-control">
            <%= @language.name %>
          </div>
        </div>
        <div class="form-group col-md-4">
          <%= link_to '編集', edit_snippet_path(@snippet.id), class: 'btn btn-dark position' %>
          <%= link_to '削除', snippet_path(@snippet.id), method: 'DELETE', data: { confirm: '削除しますか？' }, class: 'btn btn-dark position' %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-8">
          <p>コード</p>
          <pre class="prettyprint linenums"><%= @snippet.code %></pre>
        </div>
        <div class="col-sm-4">
          <p>コメント</p>
          <textarea class="form-control" rows="12" readonly wrap="off"><%= @snippet.comment %></textarea>
        </div>
      </div>
    </div>
  </div>
</div>